project_name: vulhub-cli
scoop:
  name: vulhub-cli
  commit_msg_template: Auto Update for {{ .ProjectName }} version {{ .Tag }}
release:
  prerelease: auto
  name_template: "v{{.Version}}"
before:
  hooks:
    - go mod tidy
builds:
  - id: vulhub-cli
    env:
      - CGO_ENABLED=1
      - GO111MODULE=on
      - GOFLAGS=-trimpath
      - CXX_FOR_TARGET=i686-w64-mingw32-g++
      - CC_FOR_TARGET=i686-w64-mingw32-gcc
    goos:
      - windows
    goarch:
      - amd64
    targets:
      - "windows_amd64"
checksum:
  name_template: "{{ .ProjectName }}_windows_amd64.exe.sha256"
  algorithm: sha256
archives:
  - format: binary
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
